### ISSUE TITLE
the interactions from chatbot with Sensor case are not saved for the analytics

### ISSUE THREAD

**Issue by anneliret** [isee4xai/iSeeIssueTracker#15]
I've just tried again today (4th March) with my account (annel@trial.com) on the Sensor anomaly detection case (Bosch). I went thourgh the entire interaction flow with Auditor persona. At the end, I get a message like "chatbot disconnected please try restart". So I thought my session was recorded in iSee. 

but when I go to the analytics, there is no additional record on the 4th March for my session.
I've really worried that all the trial test of people with the sensor case were lost because of some issue at the end of the chatbot.

**Comment by bfleisch** [comment]
Logs from the API container:

2024-03-05T10:34:48.908561104Z PayloadTooLargeError: request entity too large
2024-03-05T10:34:48.908598302Z     at readStream (/app/node_modules/raw-body/index.js:156:17)
2024-03-05T10:34:48.908605230Z     at getRawBody (/app/node_modules/raw-body/index.js:109:12)
2024-03-05T10:34:48.908610611Z     at read (/app/node_modules/body-parser/lib/read.js:79:3)
2024-03-05T10:34:48.908615820Z     at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)
2024-03-05T10:34:48.908620800Z     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2024-03-05T10:34:48.908625953Z     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
2024-03-05T10:34:48.908631911Z     at /app/node_modules/express/lib/router/index.js:286:9
2024-03-05T10:34:48.908637009Z     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
2024-03-05T10:34:48.908642278Z     at next (/app/node_modules/express/lib/router/index.js:280:10)
2024-03-05T10:34:48.908647391Z     at /app/node_modules/express-fileupload/lib/index.js:35:14

**Comment by anjanaw** [comment]
Thanks @bfleisch . This can be because the images are too big. This came up when executing NN explainer for this use case as well. 
I'm open to suggestions on how to solve this.

**Comment by anneliret** [comment]
Is it possible to increase the size of the structure used to store it in the database ?
Is it possible to save without the images ?
At least to not loose the interaction results.
thanks
Anne

**Comment by anjanaw** [comment]
The issue does not seem to come from the storage, its the API request body being too large. 
Also this request body includes all the explanations as well in base64.  A long term solution would be to look for a way to increase the request size. 

Saving the interaction without images is a temporary fix, which i can do just for this use case (hardcoded on the chatbot). It will have to reverted after the user studies. If you are happy to do that, let me know.

**Comment by anneliret** [comment]
Hi Anjana,

Yes removing the images from the storage will work for us, during the evaluation experiments.
Just checking, no need to regenerate the invite link once you have made the changes, right ?

Anne

**Comment by anjanaw** [comment]
No. No need to regenerate the link. I will update you once the changes are deployed.

**Comment by anjanaw** [comment]
@anneliret please test and see if the issue still exists. I have tested once, and my responses were saved correctly.

**Comment by anneliret** [comment]
Hi Anjana,

Now the invite link for v251 which is the one shared with users does not go to v251 anymore. When I log to it, the chatbot goes to v252. I've just tried and I went through the full interaction as an Auditor, at the end I had the chatbot disconnected exception again. Is it expected ?

Anne

**Comment by anjanaw** [comment]
See if it is fixed now. 
Analytics/Postman will not be working from these conversation logs. I will add a workaround for that soon. 
But you can still check if the conversation is saved from the cockpit usecases view where runs incremented.

**Comment by anjanaw** [comment]
Analytics are also updated to ignore missing data. Please test and close. @anneliret
